apiVersion: v1
kind: Service
metadata:
  name: bluegreen-svc
  labels:
    app: bluegreen-app
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001 
    protocol: TCP
  selector:
    app: bluegreen-app